### ISSUE TITLE
Create post for the Spring Boot session

### ISSUE THREAD

**Issue by ntbandara3** [sliit-foss/year-2019#6]
Create a post to be used for marketing purposes of the Spring Boot session on Friday. 

Content: 
What are Microservices? 
Introduction to REST and RESTful web services 
Introduction to Build Systems (Maven)
Spring Boot - What, Why and How? 
Building up a Spring Boot Project from the Scratch

**Comment by ntbandara3** [comment]
![WhatsApp Image 2019-07-23 at 1 23 25 AM](https://user-images@KaveeshaG thubusercontent.com/14901805/61693503-4f895c80-ad4d-11e9-9772-40bc27c72245.jpeg)

@KaveeshaG please increase the font size of the name of the speaker and the designation smaller.

**Comment by Indimagedara** [comment]
Don’t miss the chance to set your first step on Spring Boot !

Introductory session to Java Spring Boot is another episode of the series of tech talks - Tech Talk Friday, organized by the SLIIT FOSS Community.

The Spring Framework is an application framework and inversion of control container for the java platform. The Framework’s core features can be used by any Java application. There are extensions for building web applications on top of the Java EE platform.

Following content will be covered on the session.

•	What are Microservices?
•	Introduction to REST and RESTful web services
•	Introduction to Build Systems (Maven)
•	Spring Boot – What, Why and How?
•	Building up a Spring Boot Project from the Scratch


Speaker:  Ishan Yapa (Software Engineer | Pearson)

Date: 26th of July 2019
Time: 10:30AM onwards
Venue: Mini Auditorium

Note: Please bring your laptops. Power extensions and Internet connection are required.

**Comment by Indimagedara** [comment]
Done
